In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [7]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [14]:
np.linspace(0,100,31)

array([   0.        ,    3.33333333,    6.66666667,   10.        ,
         13.33333333,   16.66666667,   20.        ,   23.33333333,
         26.66666667,   30.        ,   33.33333333,   36.66666667,
         40.        ,   43.33333333,   46.66666667,   50.        ,
         53.33333333,   56.66666667,   60.        ,   63.33333333,
         66.66666667,   70.        ,   73.33333333,   76.66666667,
         80.        ,   83.33333333,   86.66666667,   90.        ,
         93.33333333,   96.66666667,  100.        ])

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
np.random.rand(5,5)

array([[ 0.03329702,  0.83082826,  0.71632613,  0.38657871,  0.55320628],
       [ 0.84758422,  0.10291214,  0.97949148,  0.24958724,  0.53548743],
       [ 0.8103471 ,  0.60158201,  0.62072285,  0.46452219,  0.02818303],
       [ 0.85962274,  0.9960727 ,  0.86768921,  0.65965537,  0.11586682],
       [ 0.80541114,  0.37205084,  0.02362461,  0.74728182,  0.71261324]])

In [20]:
np.random.randn(5,5)

array([[-0.86332479, -0.57310136, -1.54234555,  0.48810561,  0.29477882],
       [-0.03465782, -1.04723078, -1.00323089,  1.46698186,  0.82411383],
       [-0.76459351, -0.00780465, -0.00382253, -0.03558484, -1.20045585],
       [ 2.17755729,  1.4011557 , -2.25606071, -0.70345282, -1.49572338],
       [ 1.15388451,  0.32952248,  0.11944554,  0.33975138,  0.03860333]])

In [21]:
np.random.randint(1,100,10)

array([ 2, 62, 84, 60, 15, 10, 95, 58, 87, 70])

In [22]:
arr =np.arange(25)
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([37, 25,  7,  1, 11,  9, 41,  6, 40,  6])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
arr.shape

(25,)

In [28]:
arr.dtype


dtype('int32')

In [30]:
ranarr

array([37, 25,  7,  1, 11,  9, 41,  6, 40,  6])

In [31]:
ranarr.max()

41

In [32]:
ranarr.argmax()

6

In [33]:
arr = np.arange(0,10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [37]:
arr ** arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [38]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [39]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [40]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[-1]

10

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[0:5] = 100

In [47]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr = np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [51]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
mat[0]

array([ 5, 10, 15])

In [53]:
mat[2]

array([35, 40, 45])

In [54]:
mat[1,1]

25

In [55]:
mat[0,2]

15

In [56]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [61]:
arr = np.arange(1,11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr >4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [64]:
bool_arr = arr > 4

In [65]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr[arr<6]

array([1, 2, 3, 4, 5])